/* Language2025x2.java */
/* Generated By:JavaCC: Do not edit this line. Language2025x2.java */
package org.example.JavaCC;

import java.util.Set;
import java.util.TreeSet;
import java.util.HashSet;

public class Language2025x2 implements Language2025x2Constants {

    public StringBuilder errosSintaticos = new StringBuilder();
    private Token ultimoErroReportado = null;
    private boolean debug_recovery = true; // Mude para false para desativar as mensagens de debug

    public static class RecoverySet extends HashSet<Integer> {
        public RecoverySet(int... tokens) {
            for (int token : tokens) {
                this.add(token);
            }
        }
    }
    static final RecoverySet programaRecSet = new RecoverySet(START, END, DOT, EOF); // verificar
    static final RecoverySet declaracaoRecSet = new RecoverySet(SEMICOLON, START);
    static final RecoverySet comandoRecSet = new RecoverySet(SEMICOLON, END, SET, READ, SHOW, IF, LOOP);

    private String criaListaEsperados(ParseException e) {
        Set<String> tokensEsperados = new TreeSet<>();
        for (int i = 0; i < e.expectedTokenSequences.length; i++) {
            for (int j = 0; j < e.expectedTokenSequences[i].length; j++) {
                String tokenImage = e.tokenImage[e.expectedTokenSequences[i][j]];
                String tokenLimpo = tokenImage.replaceAll("^<|>$", "").replaceAll("\"", "");
                tokensEsperados.add(tokenLimpo.toLowerCase());
            }
        }
        return String.join(", ", tokensEsperados);
    }

    void reportaErro(ParseException e, String met) {
        Token t = e.currentToken.next;
        if (t == ultimoErroReportado) {
            return;
        }
        ultimoErroReportado = t;

        String encontrado = t.image;
        String esperados = criaListaEsperados(e);
        String erroMsg = String.format(
            "Erro Sint\u00e1tico na linha %d, coluna %d: Encontrado '%s', mas esperava %s\n",
            t.beginLine, t.beginColumn, encontrado, esperados);
        errosSintaticos.append(erroMsg);
        //System.err.print(erroMsg);
    }


    void consumeUntil(RecoverySet g, ParseException e, String met) {
        reportaErro(e, met); // Reporta o erro original

        if (debug_recovery) {
            System.out.println();
            System.out.println("*** Recuperando do erro em '" + met + "' ***");
            System.out.println("    Procurando por um token no conjunto: " + g);
        }

        Token tok = getToken(1); // Pega o token atual sem consumir

        while (tok.kind != EOF) {
            if (g.contains(tok.kind)) { // Achou um token de sincronização
                if (debug_recovery) {
                    System.out.println("    Encontrado token de sincroniza\u00e7\u00e3o: " + tokenImage[tok.kind]);
                    System.out.println("*** Fim da Recupera\u00e7\u00e3o ***");
                    System.out.println();
                }
                break; // Sai do laço, a recuperação terminou
            }
            if (debug_recovery) {
                System.out.println("    Ignorando token: " + tokenImage[tok.kind]);
            }
            getNextToken();      // Consome o token atual
            tok = getToken(1);   // Pega o próximo
        }
    }

  final public void programa() throws ParseException {
    trace_call("programa");
    try {

      try {
        jj_consume_token(BEGIN);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          jj_consume_token(IDENTIFIER);
          break;
          }
        default:
          jj_la1[0] = jj_gen;
          ;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case DEFINE:{
          declaracao();
          break;
          }
        default:
          jj_la1[1] = jj_gen;
          ;
        }
        jj_consume_token(START);
        listaDeComandos();
        jj_consume_token(END);
        jj_consume_token(DOT);
      } catch (ParseException e) {
consumeUntil(programaRecSet, e, "programa"); //criar recovery set

      }
    } finally {
      trace_return("programa");
    }
}

// DECLARACAO DE VARIAVEIS
  final public void declaracao() throws ParseException {
    trace_call("declaracao");
    try {

      try {
        jj_consume_token(DEFINE);
        listaDeclaracao();
      } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "declaracao");
      }
    } finally {
      trace_return("declaracao");
    }
}

  final public void listaDeclaracao() throws ParseException {
    trace_call("listaDeclaracao");
    try {

      label_1:
      while (true) {
        variosIdentificadores();
        jj_consume_token(COLON);
        tipos();
        variosTipos();
        jj_consume_token(SEMICOLON);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          ;
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          break label_1;
        }
      }
    } finally {
      trace_return("listaDeclaracao");
    }
}

  final public void variosIdentificadores() throws ParseException {
    trace_call("variosIdentificadores");
    try {

      try {
        jj_consume_token(IDENTIFIER);
        listaIdentificadores();
      } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "lista de Identificadores");
      }
    } finally {
      trace_return("variosIdentificadores");
    }
}

  final public void listaIdentificadores() throws ParseException {
    trace_call("listaIdentificadores");
    try {

      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[3] = jj_gen;
          break label_2;
        }
        jj_consume_token(COMMA);
        jj_consume_token(IDENTIFIER);
      }
    } finally {
      trace_return("listaIdentificadores");
    }
}

  final public void tipos() throws ParseException {
    trace_call("tipos");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TYPE_NUM:{
        jj_consume_token(TYPE_NUM);
        break;
        }
      case TYPE_REAL:{
        jj_consume_token(TYPE_REAL);
        break;
        }
      case TYPE_TEXT:{
        jj_consume_token(TYPE_TEXT);
        break;
        }
      case TYPE_FLAG:{
        jj_consume_token(TYPE_FLAG);
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("tipos");
    }
}

  final public void constants() throws ParseException {
    trace_call("constants");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NUM:{
        jj_consume_token(NUM);
        break;
        }
      case REAL:{
        jj_consume_token(REAL);
        break;
        }
      case TEXT:{
        jj_consume_token(TEXT);
        break;
        }
      case TRUE:{
        jj_consume_token(TRUE);
        break;
        }
      case FALSE:{
        jj_consume_token(FALSE);
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("constants");
    }
}

  final public void constantsDeclare() throws ParseException {
    trace_call("constantsDeclare");
    try {

      try {
        constants();
        constantsList();
      } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "declaracao");
      }
    } finally {
      trace_return("constantsDeclare");
    }
}

  final public void constantsList() throws ParseException {
    trace_call("constantsList");
    try {

      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          jj_consume_token(COMMA);
          constantsDeclare();
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "declaracao");
      }
    } finally {
      trace_return("constantsList");
    }
}

  final public void variosTipos() throws ParseException {
    trace_call("variosTipos");
    try {

      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ASSIGN:
        case LBRACKET:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case ASSIGN:{
            jj_consume_token(ASSIGN);
            constants();
            break;
            }
          case LBRACKET:{
            jj_consume_token(LBRACKET);
            jj_consume_token(NUM);
            jj_consume_token(RBRACKET);
            vectorDeclare();
            break;
            }
          default:
            jj_la1[7] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "declaracao");
      }
    } finally {
      trace_return("variosTipos");
    }
}

  final public void vectorDeclare() throws ParseException {
    trace_call("vectorDeclare");
    try {

      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ASSIGN:{
          jj_consume_token(ASSIGN);
          jj_consume_token(LBRACE);
          constantsDeclare();
          jj_consume_token(RBRACE);
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "declaracao");
      }
    } finally {
      trace_return("vectorDeclare");
    }
}

//Comandos
  final public 
void listaDeComandos() throws ParseException {
    trace_call("listaDeComandos");
    try {

      try {
        comando();
      } catch (ParseException e) {
consumeUntil(comandoRecSet, e, "lista de comandos");
      }
    } finally {
      trace_return("listaDeComandos");
    }
}

  final public void comando() throws ParseException {
    trace_call("comando");
    try {

      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SET:{
          atribuicao();
          break;
          }
        case READ:{
          entrada();
          break;
          }
        case SHOW:{
          saida();
          break;
          }
        case IF:{
          selecao();
          break;
          }
        case LOOP:{
          repeticao();
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SET:
        case READ:
        case SHOW:
        case IF:
        case LOOP:{
          listaDeComandos();
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(comandoRecSet, e, "lista de comandos");
      }
    } finally {
      trace_return("comando");
    }
}

  final public void atribuicao() throws ParseException {
    trace_call("atribuicao");
    try {

      jj_consume_token(SET);
      jj_consume_token(IDENTIFIER);
      vetor();
      jj_consume_token(ASSIGN);
      expressao();
      jj_consume_token(SEMICOLON);
    } finally {
      trace_return("atribuicao");
    }
}

  final public void entrada() throws ParseException {
    trace_call("entrada");
    try {

      jj_consume_token(READ);
      jj_consume_token(LPAREN);
      jj_consume_token(IDENTIFIER);
      vetor();
      jj_consume_token(RPAREN);
      jj_consume_token(SEMICOLON);
    } finally {
      trace_return("entrada");
    }
}

  final public void saida() throws ParseException {
    trace_call("saida");
    try {

      jj_consume_token(SHOW);
      jj_consume_token(LPAREN);
      idOuConst();
      jj_consume_token(RPAREN);
      jj_consume_token(SEMICOLON);
    } finally {
      trace_return("saida");
    }
}

  final public void idOuConst() throws ParseException {
    trace_call("idOuConst");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        jj_consume_token(IDENTIFIER);
        vetor();
        listaIdOuConst();
        break;
        }
      case TRUE:
      case FALSE:
      case TEXT:
      case REAL:
      case NUM:{
        constants();
        listaIdOuConst();
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("idOuConst");
    }
}

  final public void listaIdOuConst() throws ParseException {
    trace_call("listaIdOuConst");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        jj_consume_token(COMMA);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          jj_consume_token(IDENTIFIER);
          vetor();
          listaIdOuConst();
          break;
          }
        case TRUE:
        case FALSE:
        case TEXT:
        case REAL:
        case NUM:{
          constants();
          listaIdOuConst();
          break;
          }
        default:
          jj_la1[13] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        ;
      }
    } finally {
      trace_return("listaIdOuConst");
    }
}

  final public void vetor() throws ParseException {
    trace_call("vetor");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACKET:{
        jj_consume_token(LBRACKET);
        expressao();
        jj_consume_token(RBRACKET);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        ;
      }
    } finally {
      trace_return("vetor");
    }
}

  final public void expressao() throws ParseException {
    trace_call("expressao");
    try {

      expAritOuLogi();
      expressao1();
    } finally {
      trace_return("expressao");
    }
}

  final public void expressao1() throws ParseException {
    trace_call("expressao1");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQUAL:
      case NOT_EQUAL:
      case SHIFT_RIGHT_ASSIGN:
      case SHIFT_LEFT:
      case SHIFT_RIGHT:
      case SHIFT_LEFT_ASSIGN:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case EQUAL:{
          jj_consume_token(EQUAL);
          break;
          }
        case NOT_EQUAL:{
          jj_consume_token(NOT_EQUAL);
          break;
          }
        case SHIFT_LEFT:{
          jj_consume_token(SHIFT_LEFT);
          break;
          }
        case SHIFT_RIGHT:{
          jj_consume_token(SHIFT_RIGHT);
          break;
          }
        case SHIFT_LEFT_ASSIGN:{
          jj_consume_token(SHIFT_LEFT_ASSIGN);
          break;
          }
        case SHIFT_RIGHT_ASSIGN:{
          jj_consume_token(SHIFT_RIGHT_ASSIGN);
          break;
          }
        default:
          jj_la1[16] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        expAritOuLogi();
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        ;
      }
    } finally {
      trace_return("expressao1");
    }
}

  final public void expAritOuLogi() throws ParseException {
    trace_call("expAritOuLogi");
    try {

      termo2();
      menorPrioridade();
    } finally {
      trace_return("expAritOuLogi");
    }
}

  final public void menorPrioridade() throws ParseException {
    trace_call("menorPrioridade");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:
      case PIPE:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PLUS:{
          jj_consume_token(PLUS);
          break;
          }
        case MINUS:{
          jj_consume_token(MINUS);
          break;
          }
        case PIPE:{
          jj_consume_token(PIPE);
          break;
          }
        default:
          jj_la1[18] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        termo2();
        menorPrioridade();
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        ;
      }
    } finally {
      trace_return("menorPrioridade");
    }
}

  final public void termo2() throws ParseException {
    trace_call("termo2");
    try {

      termo1();
      mediaPrioridade();
    } finally {
      trace_return("termo2");
    }
}

  final public void mediaPrioridade() throws ParseException {
    trace_call("mediaPrioridade");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case STAR:
      case SLASH:
      case PERCENT:
      case DOUBLE_PERCENT:
      case AMPERSAND:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case STAR:{
          jj_consume_token(STAR);
          break;
          }
        case SLASH:{
          jj_consume_token(SLASH);
          break;
          }
        case PERCENT:{
          jj_consume_token(PERCENT);
          break;
          }
        case DOUBLE_PERCENT:{
          jj_consume_token(DOUBLE_PERCENT);
          break;
          }
        case AMPERSAND:{
          jj_consume_token(AMPERSAND);
          break;
          }
        default:
          jj_la1[20] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        termo1();
        mediaPrioridade();
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        ;
      }
    } finally {
      trace_return("mediaPrioridade");
    }
}

  final public void termo1() throws ParseException {
    trace_call("termo1");
    try {

      elemento();
      maiorPrioridade();
    } finally {
      trace_return("termo1");
    }
}

  final public void maiorPrioridade() throws ParseException {
    trace_call("maiorPrioridade");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case POWER:{
        jj_consume_token(POWER);
        elemento();
        maiorPrioridade();
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        ;
      }
    } finally {
      trace_return("maiorPrioridade");
    }
}

  final public void elemento() throws ParseException {
    trace_call("elemento");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        jj_consume_token(IDENTIFIER);
        break;
        }
      case TRUE:
      case FALSE:
      case TEXT:
      case REAL:
      case NUM:{
        constants();
        break;
        }
      case LPAREN:
      case EXCLAMATION:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case EXCLAMATION:{
          jj_consume_token(EXCLAMATION);
          break;
          }
        default:
          jj_la1[23] = jj_gen;
          ;
        }
        jj_consume_token(LPAREN);
        expressao();
        jj_consume_token(RPAREN);
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("elemento");
    }
}

  final public void repeticao() throws ParseException {
    trace_call("repeticao");
    try {

      try {
        jj_consume_token(LOOP);
        jj_consume_token(WHILE);
        expressao();
        listaDeComandos();
        jj_consume_token(END);
        jj_consume_token(SEMICOLON);
      } catch (ParseException e) {
consumeUntil(comandoRecSet, e, "lista de comandos");
      }
    } finally {
      trace_return("repeticao");
    }
}

  final public void selecao() throws ParseException {
    trace_call("selecao");
    try {

      try {
        jj_consume_token(IF);
        expressao();
        jj_consume_token(THEN);
        listaDeComandos();
        ifelse();
        jj_consume_token(END);
        jj_consume_token(SEMICOLON);
      } catch (ParseException e) {
consumeUntil(comandoRecSet, e, "lista de comandos");
      }
    } finally {
      trace_return("selecao");
    }
}

  final public void ifelse() throws ParseException {
    trace_call("ifelse");
    try {

      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ELSE:{
          jj_consume_token(ELSE);
          listaDeComandos();
          break;
          }
        default:
          jj_la1[25] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(comandoRecSet, e, "lista de comandos");
      }
    } finally {
      trace_return("ifelse");
    }
}

  /** Generated Token Manager. */
  public Language2025x2TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[26];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x100,0x0,0x0,0xf000,0xe600000,0x0,0x80000000,0x80000000,0x80000000,0x870800,0x870800,0xe600000,0xe600000,0x0,0x0,0x30000000,0x30000000,0x0,0x0,0x0,0x0,0x0,0x0,0xe600000,0x100000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x800000,0x0,0x800000,0x2,0x0,0x0,0x2,0x20,0x20,0x0,0x0,0x0,0x800000,0x800000,0x2,0x20,0xe0800,0xe0800,0x200600,0x200600,0x417000,0x417000,0x8000,0x100000,0x900080,0x0,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
	}

  {
      enable_tracing();
  }
  /** Constructor with InputStream. */
  public Language2025x2(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Language2025x2(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new Language2025x2TokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Language2025x2(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new Language2025x2TokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new Language2025x2TokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Language2025x2(Language2025x2TokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(Language2025x2TokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   trace_token(token, "");
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	   trace_token(token, " (in getNextToken)");
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[67];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 26; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 67; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  private int trace_indent = 0;
/** Enable tracing. */
  final public void enable_tracing() {
	 trace_enabled = true;
  }

/** Disable tracing. */
  final public void disable_tracing() {
	 trace_enabled = false;
  }

  protected void trace_call(String s) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Call:	" + s);
	 }
	 trace_indent = trace_indent + 2;
  }

  protected void trace_return(String s) {
	 trace_indent = trace_indent - 2;
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Return: " + s);
	 }
  }

  protected void trace_token(Token t, String where) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Consumed token: <" + tokenImage[t.kind]);
	   if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t.image) + "\"");
	   }
	   System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
	 }
  }

  protected void trace_scan(Token t1, int t2) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Visited token: <" + tokenImage[t1.kind]);
	   if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t1.image) + "\"");
	   }
	   System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
	 }
  }

}
