/* Generated By:JavaCC: Do not edit this line. Language2025x2Constants.java */
package org.example.JavaCC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Language2025x2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BEGIN = 5;
  /** RegularExpression Id. */
  int DEFINE = 6;
  /** RegularExpression Id. */
  int START = 7;
  /** RegularExpression Id. */
  int END = 8;
  /** RegularExpression Id. */
  int SET = 9;
  /** RegularExpression Id. */
  int TYPE_NUM = 10;
  /** RegularExpression Id. */
  int TYPE_REAL = 11;
  /** RegularExpression Id. */
  int TYPE_TEXT = 12;
  /** RegularExpression Id. */
  int TYPE_FLAG = 13;
  /** RegularExpression Id. */
  int READ = 14;
  /** RegularExpression Id. */
  int SHOW = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int THEN = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int TRUE = 19;
  /** RegularExpression Id. */
  int FALSE = 20;
  /** RegularExpression Id. */
  int LOOP = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int TEXT = 23;
  /** RegularExpression Id. */
  int REAL = 24;
  /** RegularExpression Id. */
  int NUM = 25;
  /** RegularExpression Id. */
  int EQUAL = 26;
  /** RegularExpression Id. */
  int NOT_EQUAL = 27;
  /** RegularExpression Id. */
  int SEMICOLON = 28;
  /** RegularExpression Id. */
  int ASSIGN = 29;
  /** RegularExpression Id. */
  int COLON = 30;
  /** RegularExpression Id. */
  int COMMA = 31;
  /** RegularExpression Id. */
  int DOT = 32;
  /** RegularExpression Id. */
  int LBRACE = 33;
  /** RegularExpression Id. */
  int RBRACE = 34;
  /** RegularExpression Id. */
  int LBRACKET = 35;
  /** RegularExpression Id. */
  int RBRACKET = 36;
  /** RegularExpression Id. */
  int LPAREN = 37;
  /** RegularExpression Id. */
  int RPAREN = 38;
  /** RegularExpression Id. */
  int PLUS = 39;
  /** RegularExpression Id. */
  int MINUS = 40;
  /** RegularExpression Id. */
  int SHIFT_RIGHT_ASSIGN = 41;
  /** RegularExpression Id. */
  int STAR = 42;
  /** RegularExpression Id. */
  int SLASH = 43;
  /** RegularExpression Id. */
  int PERCENT = 44;
  /** RegularExpression Id. */
  int POWER = 45;
  /** RegularExpression Id. */
  int DOUBLE_PERCENT = 46;
  /** RegularExpression Id. */
  int SHIFT_LEFT = 47;
  /** RegularExpression Id. */
  int SHIFT_RIGHT = 48;
  /** RegularExpression Id. */
  int SHIFT_LEFT_ASSIGN = 49;
  /** RegularExpression Id. */
  int EXCLAMATION = 50;
  /** RegularExpression Id. */
  int PIPE = 51;
  /** RegularExpression Id. */
  int AMPERSAND = 52;
  /** RegularExpression Id. */
  int IDENTIFIER = 53;
  /** RegularExpression Id. */
  int ERROR_UNTERMINATED_STRING = 54;
  /** RegularExpression Id. */
  int INVALID_SYMBOL = 55;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 56;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"begin\"",
    "\"define\"",
    "\"start\"",
    "\"end\"",
    "\"set\"",
    "\"num\"",
    "\"real\"",
    "\"text\"",
    "\"flag\"",
    "\"read\"",
    "\"show\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"loop\"",
    "\"while\"",
    "<TEXT>",
    "<REAL>",
    "<NUM>",
    "\"==\"",
    "\"!=\"",
    "\";\"",
    "\"=\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\">>=\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"**\"",
    "\"%%\"",
    "\"<<\"",
    "\">>\"",
    "\"<<=\"",
    "\"!\"",
    "\"|\"",
    "\"&\"",
    "<IDENTIFIER>",
    "<ERROR_UNTERMINATED_STRING>",
    "<INVALID_SYMBOL>",
    "<SINGLE_LINE_COMMENT>",
    "<BLOCK_COMMENT>",
  };

}
