/* Language2025x2.java */
/* Generated By:JavaCC: Do not edit this line. Language2025x2.java */
package org.example.JavaCC;

import org.example.Actions.AnalisadorSemantico;
import java.util.Set;
import java.util.TreeSet;
import java.util.HashSet;

public class Language2025x2 implements Language2025x2Constants {
    public AnalisadorSemantico semantico = new AnalisadorSemantico();
    public StringBuilder errosSintaticos = new StringBuilder();
    private Token ultimoErroReportado = null;
    private boolean debug_recovery = true; // Mude para false para desativar as mensagens de debug

    public static class RecoverySet extends HashSet<Integer> {
        public RecoverySet(int... tokens) {
            for (int token : tokens) {
                this.add(token);
            }
        }
    }
    static final RecoverySet programaRecSet = new RecoverySet(START, END, DOT, EOF); // verificar
    static final RecoverySet declaracaoRecSet = new RecoverySet(SEMICOLON, START);
    static final RecoverySet comandoRecSet = new RecoverySet(SEMICOLON, END, SET, READ, SHOW, IF, LOOP);

    private String criaListaEsperados(ParseException e) {
        Set<String> tokensEsperados = new TreeSet<>();
        for (int i = 0; i < e.expectedTokenSequences.length; i++) {
            for (int j = 0; j < e.expectedTokenSequences[i].length; j++) {
                String tokenImage = e.tokenImage[e.expectedTokenSequences[i][j]];
                String tokenLimpo = tokenImage.replaceAll("^<|>$", "").replaceAll("\"", "");
                tokensEsperados.add("@"+tokenLimpo.toLowerCase());
            }
        }
        return String.join(", ", tokensEsperados);
    }

    void reportaErroSintatico(ParseException e, String met) {
        Token t = e.currentToken.next;
        if (t == ultimoErroReportado) {
            return;
        }
        ultimoErroReportado = t;

        String encontrado = t.image;
        String esperados = criaListaEsperados(e);
        String erroMsg = String.format(
            "<div class='log-entry'><span class='line-info'>Erro Sint\u00e1tico na linha %d, coluna %d:</span><br> Encontrado <span class='found'>@%s</span> mas esperava <span class='expected'>@%s</span></div>\n",
            t.beginLine, t.beginColumn, encontrado.equals("@") || encontrado.equals("@ ") || encontrado.equals(" ") || encontrado.isEmpty() ? "espaco" : encontrado, esperados);
        errosSintaticos.append(erroMsg);
        //System.err.print(erroMsg);
    }


    void consumeUntil(RecoverySet g, ParseException e, String met) {
        reportaErroSintatico(e, met); // Reporta o erro original

        if (debug_recovery) {
            System.out.println();
            System.out.println("*** Recuperando do erro em '" + met + "' ***");
            System.out.println("    Procurando por um token no conjunto: " + g);
        }

        Token tok = getToken(1); // Pega o token atual sem consumir

        while (tok.kind != EOF) {
            if (g.contains(tok.kind)) { // Achou um token de sincronização
                if (debug_recovery) {
                    System.out.println("    Encontrado token de sincroniza\u00e7\u00e3o: " + tokenImage[tok.kind]);
                    System.out.println("*** Fim da Recupera\u00e7\u00e3o ***");
                    System.out.println();
                }
                break; // Sai do laço, a recuperação terminou
            }
            if (debug_recovery) {
                System.out.println("    Ignorando token: " + tokenImage[tok.kind]);
            }
            getNextToken();      // Consome o token atual
            tok = getToken(1);   // Pega o próximo
        }
    }

  final public void programa() throws ParseException {Token identificadorToken;
    try {
      jj_consume_token(BEGIN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        identificadorToken = jj_consume_token(IDENTIFIER);
semantico.programa1(identificadorToken);
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DEFINE:{
        declaracao();
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        ;
      }
      jj_consume_token(START);
      listaDeComandos();
semantico.programa2();
      jj_consume_token(END);
      jj_consume_token(DOT);
    } catch (ParseException e) {
consumeUntil(programaRecSet, e, "programa"); //criar recovery set

    }
}

// DECLARACAO DE VARIAVEIS
  final public void declaracao() throws ParseException {
    try {
      jj_consume_token(DEFINE);
semantico.declaracao0();
      listaDeclaracao();
    } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "declaracao");
    }
}

  final public void listaDeclaracao() throws ParseException {
    label_1:
    while (true) {
      variosIdentificadores();
      jj_consume_token(COLON);
      tipos();
      variosTipos();
      jj_consume_token(SEMICOLON);
semantico.declaracao6();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_1;
      }
    }
}

  final public void variosIdentificadores() throws ParseException {Token identificadorToken;
    try {
      identificadorToken = jj_consume_token(IDENTIFIER);
semantico.declaracao1(identificadorToken);
      listaIdentificadores();
    } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "lista de Identificadores");
    }
}

  final public void listaIdentificadores() throws ParseException {Token identificadorToken;
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      jj_consume_token(COMMA);
      identificadorToken = jj_consume_token(IDENTIFIER);
semantico.declaracao1(identificadorToken);
    }
}

  final public void tipos() throws ParseException {Token tipoToken;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TYPE_NUM:{
      tipoToken = jj_consume_token(TYPE_NUM);
semantico.tipo(tipoToken);
      break;
      }
    case TYPE_REAL:{
      tipoToken = jj_consume_token(TYPE_REAL);
semantico.tipo(tipoToken);
      break;
      }
    case TYPE_TEXT:{
      tipoToken = jj_consume_token(TYPE_TEXT);
semantico.tipo(tipoToken);
      break;
      }
    case TYPE_FLAG:{
      tipoToken = jj_consume_token(TYPE_FLAG);
semantico.tipo(tipoToken);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void constants() throws ParseException {Token constant;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUM:{
      constant = jj_consume_token(NUM);
semantico.constanteInteira(constant);
      break;
      }
    case REAL:{
      constant = jj_consume_token(REAL);
semantico.constanteReal(constant);
      break;
      }
    case TEXT:{
      constant = jj_consume_token(TEXT);
semantico.constanteLiteral(constant);
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
semantico.constanteVerdadeira();
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
semantico.constanteFalsa();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void constantsDeclare() throws ParseException {
    try {
      constants();
      constantsList();
    } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "declaracao");
    }
}

  final public void constantsList() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        jj_consume_token(COMMA);
        constantsDeclare();
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        ;
      }
    } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "declaracao");
    }
}

  final public void constantsDeclareVetor() throws ParseException {
    try {
      constants();
semantico.val();
      constantsListVetor();
    } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "declaracao");
    }
}

  final public void constantsListVetor() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        jj_consume_token(COMMA);
        constantsDeclareVetor();
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        ;
      }
    } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "declaracao");
    }
}

  final public void variosTipos() throws ParseException {Token valorVetorToken;
    try {
semantico.escalar2();
      iniciaEscalar();
    } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "declaracao");
    }
}

  final public void iniciaEscalar() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ASSIGN:{
        jj_consume_token(ASSIGN);
        constantsDeclare();
semantico.inicializaEscalar();
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        ;
      }
    } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "declaracao");
    }
}

  final public void vectorDeclare() throws ParseException {Token brace;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ASSIGN:{
        jj_consume_token(ASSIGN);
        jj_consume_token(LBRACE);
        constantsDeclareVetor();
        brace = jj_consume_token(RBRACE);
semantico.inicializaVet(brace);
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        ;
      }
    } catch (ParseException e) {
consumeUntil(declaracaoRecSet, e, "declaracao");
    }
}

//Comandos
  final public 
void listaDeComandos() throws ParseException {
    try {
      comando();
    } catch (ParseException e) {
consumeUntil(comandoRecSet, e, "lista de comandos");
    }
}

  final public void comando() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SET:{
        atribuicao();
        break;
        }
      case READ:{
        entrada();
        break;
        }
      case SHOW:{
        saida();
        break;
        }
      case IF:{
        selecao();
        break;
        }
      case LOOP:{
        repeticao();
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SET:
      case READ:
      case SHOW:
      case IF:
      case LOOP:{
        listaDeComandos();
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        ;
      }
    } catch (ParseException e) {
consumeUntil(comandoRecSet, e, "lista de comandos");
    }
}

  final public void atribuicao() throws ParseException {Token id;
    jj_consume_token(SET);
    id = jj_consume_token(IDENTIFIER);
semantico.atribuicao1(id);
    vetor();
semantico.atribuicao2(id);
    jj_consume_token(ASSIGN);
    expressao();
semantico.atribuicao3();
    jj_consume_token(SEMICOLON);
}

  final public void entrada() throws ParseException {
    jj_consume_token(READ);
    jj_consume_token(LPAREN);
    jj_consume_token(IDENTIFIER);
    vetor();
    jj_consume_token(RPAREN);
    jj_consume_token(SEMICOLON);
}

  final public void saida() throws ParseException {
    jj_consume_token(SHOW);
    jj_consume_token(LPAREN);
    listaDeSaida();
    jj_consume_token(RPAREN);
    jj_consume_token(SEMICOLON);
}

  final public void listaDeSaida() throws ParseException {
    item();
    listaDeSaida1();
}

  final public void listaDeSaida1() throws ParseException {Token id;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMMA:{
      jj_consume_token(COMMA);
      item();
      listaDeSaida1();
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      ;
    }
}

  final public void item() throws ParseException {Token id;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      id = jj_consume_token(IDENTIFIER);
semantico.show2(id);
      vetor();
semantico.show3();
      break;
      }
    case NUM:{
      id = jj_consume_token(NUM);
semantico.saidaConstInteira(id);
      break;
      }
    case REAL:{
      id = jj_consume_token(REAL);
semantico.saidaConstReal(id);
      break;
      }
    case TEXT:{
      id = jj_consume_token(TEXT);
semantico.saidaConstLiteral(id);
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void vetor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACKET:{
      jj_consume_token(LBRACKET);
      expressao();
semantico.i1();
      jj_consume_token(RBRACKET);
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      ;
    }
}

  final public void expressao() throws ParseException {
    expAritOuLogi();
    expressao1();
}

  final public void expressao1() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EQUAL:
    case NOT_EQUAL:
    case SHIFT_RIGHT_ASSIGN:
    case SHIFT_LEFT:
    case SHIFT_RIGHT:
    case SHIFT_LEFT_ASSIGN:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQUAL:{
        jj_consume_token(EQUAL);
        expAritOuLogi();
semantico.rIgual();
        break;
        }
      case NOT_EQUAL:{
        jj_consume_token(NOT_EQUAL);
        expAritOuLogi();
semantico.rDiferente();
        break;
        }
      case SHIFT_LEFT:{
        jj_consume_token(SHIFT_LEFT);
        expAritOuLogi();
semantico.rMenor();
        break;
        }
      case SHIFT_RIGHT:{
        jj_consume_token(SHIFT_RIGHT);
        expAritOuLogi();
semantico.rMaior();
        break;
        }
      case SHIFT_LEFT_ASSIGN:{
        jj_consume_token(SHIFT_LEFT_ASSIGN);
        expAritOuLogi();
semantico.rMenorIgual();
        break;
        }
      case SHIFT_RIGHT_ASSIGN:{
        jj_consume_token(SHIFT_RIGHT_ASSIGN);
        expAritOuLogi();
semantico.rMaiorIgual();
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
}

  final public void expAritOuLogi() throws ParseException {
    termo2();
    menorPrioridade();
}

  final public void menorPrioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:
    case MINUS:
    case PIPE:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        jj_consume_token(PLUS);
        termo2();
semantico.rAdd();
        menorPrioridade();
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
        termo2();
semantico.rSub();
        menorPrioridade();
        break;
        }
      case PIPE:{
        jj_consume_token(PIPE);
        termo2();
semantico.rOr();
        menorPrioridade();
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      ;
    }
}

  final public void termo2() throws ParseException {
    termo1();
    mediaPrioridade();
}

  final public void mediaPrioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STAR:
    case SLASH:
    case PERCENT:
    case DOUBLE_PERCENT:
    case AMPERSAND:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case STAR:{
        jj_consume_token(STAR);
        termo1();
semantico.rMul();
        mediaPrioridade();
        break;
        }
      case SLASH:{
        jj_consume_token(SLASH);
        termo1();
semantico.rDiv();
        mediaPrioridade();
        break;
        }
      case PERCENT:{
        jj_consume_token(PERCENT);
        termo1();
semantico.rMod();
        mediaPrioridade();
        break;
        }
      case DOUBLE_PERCENT:{
        jj_consume_token(DOUBLE_PERCENT);
        termo1();
semantico.rRem();
        mediaPrioridade();
        break;
        }
      case AMPERSAND:{
        jj_consume_token(AMPERSAND);
        termo1();
semantico.rAnd();
        mediaPrioridade();
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      ;
    }
}

  final public void termo1() throws ParseException {
    elemento();
    maiorPrioridade();
}

  final public void maiorPrioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case POWER:{
      jj_consume_token(POWER);
      elemento();
semantico.rPow();
      maiorPrioridade();
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      ;
    }
}

  final public void elemento() throws ParseException {Token identToken; Token vetor;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      identToken = jj_consume_token(IDENTIFIER);
semantico.expressao1(identToken);
      vetor();
semantico.expressao2();
      break;
      }
    case TRUE:
    case FALSE:
    case TEXT:
    case REAL:
    case NUM:{
      constants();
      break;
      }
    case EXCLAMATION:{
      jj_consume_token(EXCLAMATION);
      jj_consume_token(LPAREN);
      expressao();
      jj_consume_token(RPAREN);
semantico.rNot();
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
      expressao();
      jj_consume_token(RPAREN);
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void repeticao() throws ParseException {
    try {
      jj_consume_token(LOOP);
      jj_consume_token(WHILE);
      expressao();
semantico.loop1();
      listaDeComandos();
semantico.loop2();
      jj_consume_token(END);
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
consumeUntil(comandoRecSet, e, "lista de comandos");
    }
}

  final public void selecao() throws ParseException {
    try {
      jj_consume_token(IF);
      expressao();
semantico.selecaoF1();
      jj_consume_token(THEN);
      listaDeComandos();
      ifelse();
semantico.selecaoF3();
      jj_consume_token(END);
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
consumeUntil(comandoRecSet, e, "lista de comandos");
    }
}

  final public void ifelse() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ELSE:{
        jj_consume_token(ELSE);
semantico.selecaoF2();
        listaDeComandos();
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        ;
      }
    } catch (ParseException e) {
consumeUntil(comandoRecSet, e, "lista de comandos");
    }
}

  /** Generated Token Manager. */
  public Language2025x2TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[24];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x100,0x0,0x0,0xf000,0xe600000,0x0,0x0,0x80000000,0x80000000,0x870800,0x870800,0x0,0xe000000,0x0,0x30000000,0x30000000,0x0,0x0,0x0,0x0,0x0,0xe600000,0x100000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x800000,0x0,0x800000,0x2,0x0,0x0,0x2,0x2,0x0,0x0,0x0,0x0,0x2,0x800000,0x20,0xe0800,0xe0800,0x200600,0x200600,0x417000,0x417000,0x8000,0x900080,0x0,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
	}

  /** Constructor with InputStream. */
  public Language2025x2(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Language2025x2(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new Language2025x2TokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Language2025x2(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new Language2025x2TokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new Language2025x2TokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Language2025x2(Language2025x2TokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(Language2025x2TokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[67];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 24; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 67; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
