/* CompiladorTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. CompiladorTokenManager.java */
import java.util.List;

/** Token Manager. */
@SuppressWarnings ("unused")
public class CompiladorTokenManager implements CompiladorConstants {
    int countLexError = 0;
    StringBuilder errosLexicos = new StringBuilder();

    public int multilineCommentStartLine = -1;
    public int multilineCommentStartColumn = -1;

    public int getLexErrorCount() {
        return countLexError;
    }

    public String getErrosLexicos() {
        return errosLexicos.toString();
    }

    public void checkUnclosedMultilineComment() {
        if (curLexState == CompiladorConstants.MULTILINE_COMMENT) {
            errosLexicos.append("Erro l\u00e9xico: Coment\u00e1rio de bloco n\u00e3o foi fechado. ")
                .append("Coment\u00e1rio aberto na linha ").append(multilineCommentStartLine)
                .append(", coluna ").append(multilineCommentStartColumn).append(".\n");
            System.out.println("entrou aqui, erro coment\u00e1rio de bloco. Erros l\u00e9xicos: " + countLexError++);
        }
    }

    public boolean isTokenIgnored(Token token) {
        return "/*".equals(token.image);
    }

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_1(){
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_1(0x200L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_1(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(1, 9);
         break;
      default :
         return 2;
   }
   return 2;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 9:
         jjmatchedKind = 2;
         return jjMoveNfa_0(12, 0);
      case 10:
         jjmatchedKind = 3;
         return jjMoveNfa_0(12, 0);
      case 12:
         jjmatchedKind = 5;
         return jjMoveNfa_0(12, 0);
      case 13:
         jjmatchedKind = 4;
         return jjMoveNfa_0(12, 0);
      case 32:
         jjmatchedKind = 1;
         return jjMoveNfa_0(12, 0);
      case 33:
         jjmatchedKind = 51;
         return jjMoveNfa_0(12, 0);
      case 37:
         jjmatchedKind = 42;
         return jjMoveStringLiteralDfa1_0(0x80000000000L);
      case 38:
         jjmatchedKind = 49;
         return jjMoveNfa_0(12, 0);
      case 40:
         jjmatchedKind = 35;
         return jjMoveNfa_0(12, 0);
      case 41:
         jjmatchedKind = 36;
         return jjMoveNfa_0(12, 0);
      case 42:
         jjmatchedKind = 39;
         return jjMoveStringLiteralDfa1_0(0x20000000000L);
      case 43:
         jjmatchedKind = 37;
         return jjMoveNfa_0(12, 0);
      case 44:
         jjmatchedKind = 30;
         return jjMoveNfa_0(12, 0);
      case 45:
         jjmatchedKind = 38;
         return jjMoveStringLiteralDfa1_0(0x400000000L);
      case 46:
         jjmatchedKind = 29;
         return jjMoveNfa_0(12, 0);
      case 47:
         jjmatchedKind = 40;
         return jjMoveStringLiteralDfa1_0(0xc0L);
      case 58:
         jjmatchedKind = 32;
         return jjMoveNfa_0(12, 0);
      case 59:
         jjmatchedKind = 31;
         return jjMoveNfa_0(12, 0);
      case 60:
         jjmatchedKind = 45;
         return jjMoveStringLiteralDfa1_0(0x900000000000L);
      case 61:
         jjmatchedKind = 33;
         return jjMoveNfa_0(12, 0);
      case 62:
         jjmatchedKind = 46;
         return jjMoveStringLiteralDfa1_0(0x1000000000000L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x6000L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x18000L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x20000L);
      case 71:
         return jjMoveStringLiteralDfa1_0(0x40000L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x180000L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x3000000L);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 87:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x6000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x18000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x20000L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x40000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x180000L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x3000000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 124:
         jjmatchedKind = 50;
         return jjMoveNfa_0(12, 0);
      default :
         return jjMoveNfa_0(12, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(12, 0);
   }
   switch(curChar)
   {
      case 37:
         if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 1;
         }
         break;
      case 42:
         if ((active0 & 0x80L) != 0L)
         {
            jjmatchedKind = 7;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 1;
         }
         break;
      case 47:
         if ((active0 & 0x40L) != 0L)
         {
            jjmatchedKind = 6;
            jjmatchedPos = 1;
         }
         break;
      case 61:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 1;
         }
         break;
      case 62:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 1;
         }
         break;
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x4220000L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x840000L);
      case 70:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 1;
         }
         break;
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0x9002000L);
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x110000L);
      case 79:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x5000L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x4220000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x840000L);
      case 102:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 1;
         }
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x9002000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x110000L);
      case 111:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x5000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000L);
      default :
         break;
   }
   return jjMoveNfa_0(12, 1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(12, 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(12, 1);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x802000L);
      case 68:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 2;
         }
         break;
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      case 75:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L);
      case 82:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 2;
         }
         break;
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
      case 84:
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 2;
         }
         break;
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x802000L);
      case 100:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 2;
         }
         break;
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      case 107:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L);
      case 114:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 2;
         }
         break;
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
      case 116:
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 2;
         }
         break;
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjMoveNfa_0(12, 2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(12, 2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(12, 2);
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 3;
         }
         break;
      case 76:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      case 78:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 3;
         }
         break;
      case 82:
         if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 3;
         }
         break;
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x24000L);
      case 101:
         if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 3;
         }
         break;
      case 108:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      case 110:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 3;
         }
         break;
      case 114:
         if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 3;
         }
         break;
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x24000L);
      default :
         break;
   }
   return jjMoveNfa_0(12, 3);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(12, 3);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(12, 3);
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 4;
         }
         break;
      case 84:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 4;
         }
         break;
      case 101:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 4;
         }
         break;
      case 116:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 4;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(12, 4);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int strKind = jjmatchedKind;
   int strPos = jjmatchedPos;
   int seenUpto;
   input_stream.backup(seenUpto = curPos + 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { throw new Error("Internal Error"); }
   curPos = 0;
   int startsAt = 0;
   jjnewStateCnt = 94;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 12:
                  if ((0x8000409cffffd9ffL & l) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 54)
                        kind = 54;
                     { jjCheckNAddStates(0, 16); }
                  }
                  if ((0x8000009cffffc9ffL & l) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     { jjCheckNAdd(0); }
                  }
                  if (curChar == 39)
                     { jjCheckNAddStates(17, 24); }
                  else if (curChar == 34)
                     { jjCheckNAddStates(25, 32); }
                  break;
               case 0:
                  if ((0x8000009cffffc9ffL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  { jjCheckNAdd(0); }
                  break;
               case 1:
                  if ((0x8000409cffffd9ffL & l) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(33, 35); }
                  break;
               case 3:
                  if ((0xfc00bffeffffd9ffL & l) != 0L)
                     { jjCheckNAddTwoStates(3, 4); }
                  break;
               case 4:
                  if (curChar == 46)
                     { jjCheckNAddTwoStates(5, 6); }
                  break;
               case 5:
                  if ((0xfc00bffeffffd9ffL & l) != 0L)
                     { jjCheckNAddTwoStates(5, 6); }
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  { jjCheckNAddTwoStates(7, 8); }
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  { jjCheckNAdd(8); }
                  break;
               case 8:
                  if ((0x8000009cffffd9ffL & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  { jjCheckNAdd(8); }
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(36, 39); }
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(3, 4); }
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(40, 42); }
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  { jjCheckNAddTwoStates(18, 20); }
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  { jjCheckNAdd(20); }
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjAddStates(43, 44); }
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) != 0L && kind > 57)
                     kind = 57;
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 54)
                     kind = 54;
                  { jjCheckNAddStates(0, 16); }
                  break;
               case 24:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) != 0L && kind > 53)
                     kind = 53;
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(30); }
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(30, 31); }
                  break;
               case 31:
                  if (curChar != 46)
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) != 0L && kind > 64)
                     kind = 64;
                  break;
               case 34:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(37); }
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 65)
                     kind = 65;
                  { jjCheckNAdd(37); }
                  break;
               case 38:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 39:
               case 47:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(40, 41); }
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(41); }
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(45); }
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(45, 46); }
                  break;
               case 46:
                  if (curChar == 46)
                     { jjCheckNAddTwoStates(41, 47); }
                  break;
               case 48:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(51); }
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(51, 41); }
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(54); }
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 68)
                     kind = 68;
                  { jjCheckNAdd(54); }
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddStates(45, 47); }
                  break;
               case 56:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAdd(57); }
                  break;
               case 57:
                  if ((0x8000009cffffd9ffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAdd(57); }
                  break;
               case 58:
                  if ((0x8000009cffffd9ffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddStates(45, 47); }
                  break;
               case 59:
                  if ((0x8000009cffffd9ffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddStates(48, 52); }
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(53, 55); }
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(48); }
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(61, 48); }
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(56, 58); }
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(38); }
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(64, 38); }
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(59, 61); }
                  break;
               case 67:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(34); }
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(67, 34); }
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 54)
                     kind = 54;
                  jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 70:
                  if ((0x3ff000000000000L & l) != 0L && kind > 54)
                     kind = 54;
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(62, 64); }
                  break;
               case 72:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(24); }
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(72, 24); }
                  break;
               case 74:
                  if (curChar == 34)
                     { jjCheckNAddStates(25, 32); }
                  break;
               case 75:
                  if ((0xfffffffbfffffbffL & l) != 0L)
                     { jjCheckNAddTwoStates(75, 76); }
                  break;
               case 76:
                  if (curChar == 34 && kind > 55)
                     kind = 55;
                  break;
               case 77:
                  if ((0xfffffffbfffffbffL & l) != 0L)
                     { jjCheckNAddTwoStates(77, 78); }
                  break;
               case 78:
                  if (curChar != 34)
                     break;
                  if (kind > 58)
                     kind = 58;
                  { jjCheckNAdd(79); }
                  break;
               case 79:
                  if ((0x3ff008400000000L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  { jjCheckNAdd(79); }
                  break;
               case 80:
                  if ((0xfffffffbffffd9ffL & l) != 0L)
                     { jjCheckNAddTwoStates(80, 81); }
                  break;
               case 81:
                  if ((0xfffffffbffffffffL & l) != 0L && kind > 59)
                     kind = 59;
                  break;
               case 82:
                  if ((0xfffffffbffffd9ffL & l) != 0L)
                     { jjCheckNAddTwoStates(82, 83); }
                  break;
               case 83:
                  if (curChar == 39 && kind > 61)
                     kind = 61;
                  break;
               case 84:
                  if (curChar == 39)
                     { jjCheckNAddStates(17, 24); }
                  break;
               case 85:
                  if ((0xffffff7ffffffbffL & l) != 0L)
                     { jjCheckNAddTwoStates(85, 86); }
                  break;
               case 86:
                  if (curChar == 39 && kind > 55)
                     kind = 55;
                  break;
               case 87:
                  if ((0xffffff7ffffffbffL & l) != 0L)
                     { jjCheckNAddTwoStates(87, 88); }
                  break;
               case 88:
                  if (curChar != 39)
                     break;
                  if (kind > 58)
                     kind = 58;
                  { jjCheckNAdd(89); }
                  break;
               case 89:
                  if ((0x3ff008400000000L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  { jjCheckNAdd(89); }
                  break;
               case 90:
                  if ((0xffffff7fffffd9ffL & l) != 0L)
                     { jjCheckNAddTwoStates(90, 91); }
                  break;
               case 91:
                  if ((0xffffff7fffffffffL & l) != 0L && kind > 60)
                     kind = 60;
                  break;
               case 92:
                  if ((0xffffff7fffffd9ffL & l) != 0L)
                     { jjCheckNAddTwoStates(92, 93); }
                  break;
               case 93:
                  if (curChar == 34 && kind > 62)
                     kind = 62;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 12:
                  if ((0xefffffffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 52)
                        kind = 52;
                     { jjCheckNAddStates(65, 70); }
                  }
                  if ((0xe8000001f8000001L & l) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     { jjCheckNAdd(0); }
                  }
                  break;
               case 0:
                  if ((0xe8000001f8000001L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  { jjCheckNAdd(0); }
                  break;
               case 1:
                  if ((0xefffffffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 3:
                  { jjAddStates(71, 72); }
                  break;
               case 5:
                  { jjAddStates(73, 74); }
                  break;
               case 8:
                  if ((0xefffffffffffffffL & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 13:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 52)
                     kind = 52;
                  { jjCheckNAddTwoStates(13, 14); }
                  break;
               case 15:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 52)
                     kind = 52;
                  { jjCheckNAddTwoStates(14, 16); }
                  break;
               case 16:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 52)
                     kind = 52;
                  { jjCheckNAddStates(75, 77); }
                  break;
               case 17:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 20:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 21:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(21, 22); }
                  break;
               case 41:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 57:
                  if ((0xefffffffffffffffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAdd(57); }
                  break;
               case 58:
                  if ((0xefffffffffffffffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddStates(45, 47); }
                  break;
               case 59:
                  if ((0xefffffffffffffffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddStates(48, 52); }
                  break;
               case 75:
                  { jjAddStates(78, 79); }
                  break;
               case 77:
                  { jjAddStates(80, 81); }
                  break;
               case 79:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 80:
                  { jjAddStates(82, 83); }
                  break;
               case 81:
                  if (kind > 59)
                     kind = 59;
                  break;
               case 82:
                  { jjAddStates(84, 85); }
                  break;
               case 85:
                  { jjAddStates(86, 87); }
                  break;
               case 87:
                  { jjAddStates(88, 89); }
                  break;
               case 89:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 90:
                  { jjAddStates(90, 91); }
                  break;
               case 91:
                  if (kind > 60)
                     kind = 60;
                  break;
               case 92:
                  { jjAddStates(92, 93); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 12:
                  if ((jjbitVec0[i2] & l2) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     { jjCheckNAdd(0); }
                  }
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 0:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  { jjCheckNAdd(0); }
                  break;
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 3:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(71, 72); }
                  break;
               case 5:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(73, 74); }
                  break;
               case 8:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 57:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAdd(57); }
                  break;
               case 58:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddStates(45, 47); }
                  break;
               case 59:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddStates(48, 52); }
                  break;
               case 75:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(78, 79); }
                  break;
               case 77:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(80, 81); }
                  break;
               case 80:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(82, 83); }
                  break;
               case 81:
                  if ((jjbitVec0[i2] & l2) != 0L && kind > 59)
                     kind = 59;
                  break;
               case 82:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(84, 85); }
                  break;
               case 85:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(86, 87); }
                  break;
               case 87:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(88, 89); }
                  break;
               case 90:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(90, 91); }
                  break;
               case 91:
                  if ((jjbitVec0[i2] & l2) != 0L && kind > 60)
                     kind = 60;
                  break;
               case 92:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(92, 93); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 94 - (jjnewStateCnt = startsAt)))
         break;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { break; }
   }
   if (jjmatchedPos > strPos)
      return curPos;

   int toRet = Math.max(curPos, seenUpto);

   if (curPos < toRet)
      for (i = toRet - Math.min(curPos, seenUpto); i-- > 0; )
         try { curChar = input_stream.readChar(); }
         catch(java.io.IOException e) { throw new Error("Internal Error : Please send a bug report."); }

   if (jjmatchedPos < strPos)
   {
      jjmatchedKind = strKind;
      jjmatchedPos = strPos;
   }
   else if (jjmatchedPos == strPos && jjmatchedKind > strKind)
      jjmatchedKind = strKind;

   return toRet;
}
private int jjMoveStringLiteralDfa0_2()
{
   return jjMoveNfa_2(0, 0);
}
private int jjMoveNfa_2(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 1;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x2400L & l) != 0L)
                     kind = 10;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 1 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, "\56", "\54", "\73", "\72", "\75", "\55\76", "\50", "\51", "\53", "\55", 
"\52", "\57", "\52\52", "\45", "\45\45", "\74\76", "\74", "\76", "\74\75", "\76\75", 
"\46", "\174", "\41", null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   24, 3, 4, 27, 34, 38, 42, 48, 52, 55, 59, 60, 63, 66, 9, 69, 
   71, 85, 86, 87, 88, 90, 91, 92, 93, 75, 76, 77, 78, 80, 81, 82, 
   83, 3, 4, 9, 10, 3, 4, 11, 10, 3, 4, 21, 22, 56, 57, 58, 
   56, 57, 58, 55, 59, 61, 48, 62, 64, 38, 65, 67, 34, 68, 72, 24, 
   73, 13, 14, 17, 18, 21, 22, 3, 4, 5, 6, 13, 14, 16, 75, 76, 
   77, 78, 80, 81, 82, 83, 85, 86, 87, 88, 90, 91, 92, 93, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   switch(curLexState)
   {
     case 0:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       if (jjmatchedPos == 0 && jjmatchedKind > 8)
       {
          jjmatchedKind = 8;
       }
       break;
     case 2:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_2();
       if (jjmatchedPos == 0 && jjmatchedKind > 11)
       {
          jjmatchedKind = 11;
       }
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           matchedToken.specialToken = specialToken;
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else
        {
           if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
           {
              matchedToken = jjFillToken();
              if (specialToken == null)
                 specialToken = matchedToken;
              else
              {
                 matchedToken.specialToken = specialToken;
                 specialToken = (specialToken.next = matchedToken);
              }
              SkipLexicalActions(matchedToken);
           }
           else
              SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 7 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        multilineCommentStartLine = input_stream.getBeginLine();
        multilineCommentStartColumn = input_stream.getBeginColumn();
        SwitchTo(MULTILINE_COMMENT);
         break;
      case 9 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
           SwitchTo(DEFAULT);
         break;
      case 10 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                       SwitchTo(DEFAULT);
         break;
      case 56 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // System.err.println("Linha: " + input_stream.getEndLine() + ", Coluna: " + input_stream.getEndColumn() + " - Invalid string found: " + image);
        errosLexicos.append("Erro l\u00e9xico: S\u00edmbolo desconhecido -> Token: ").append(image).append(", Linha: ").append(input_stream.getEndLine()).append(", Coluna: ").append(input_stream.getEndColumn()).append("\n");
        countLexError++;
         break;
      case 57 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // System.err.println("Linha: " + input_stream.getEndLine() + ", Coluna: " + input_stream.getEndColumn() + " - Identificador inválido: " + image);
        errosLexicos.append("Erro l\u00e9xico: Identificador inv\u00e1lido -> Token: ").append(image).append(", Linha: ").append(input_stream.getEndLine()).append(", Coluna: ").append(input_stream.getEndColumn()).append("\n");
        countLexError++;
         break;
      case 58 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // System.err.println("Linha: " + input_stream.getEndLine() + ", Coluna: " + input_stream.getEndColumn() + " - Constante literal inválida: " + image);
        System.out.println("literal 1");
        errosLexicos.append("Erro l\u00e9xico: Constante literal inv\u00e1lida -> Token: ").append(image).append(", Linha: ").append(input_stream.getEndLine()).append(", Coluna: ").append(input_stream.getEndColumn()).append("\n");
        countLexError++;
         break;
      case 59 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // System.err.println("Linha: " + input_stream.getEndLine() + ", Coluna: " + input_stream.getEndColumn() + " - Constante literal inválida: começa com '\"' e não termina com '\"': " + image);
        errosLexicos.append("Erro l\u00e9xico: Constante literal inv\u00e1lida -> come\u00e7a com '\"' e n\u00e3o termina com '\"' -> Token: ").append(image).append(", Linha: ").append(input_stream.getEndLine()).append(", Coluna: ").append(input_stream.getEndColumn()).append("\n");
        countLexError++;
         break;
      case 60 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // System.err.println("Linha: " + input_stream.getEndLine() + ", Coluna: " + input_stream.getEndColumn() + " - Constante literal inválida: começa com '\'' e não termina com '\'' : " + image);
        errosLexicos.append("Erro l\u00e9xico: Constante literal inv\u00e1lida -> come\u00e7a com '\'' e n\u00e3o termina com '\'' -> Token: ").append(image).append(", Linha: ").append(input_stream.getEndLine()).append(", Coluna: ").append(input_stream.getEndColumn()).append("\n");
        countLexError++;
         break;
      case 61 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // System.err.println("Linha: " + input_stream.getEndLine() + ", Coluna: " + input_stream.getEndColumn() + " - Constante literal inválida: começa com '\"' e termina com '\'' : " + image);
        errosLexicos.append("Erro l\u00e9xico: Constante literal inv\u00e1lida -> come\u00e7a com '\"' e termina com ' -> Token: ").append(image).append(", Linha: ").append(input_stream.getEndLine()).append(", Coluna: ").append(input_stream.getEndColumn()).append("\n");
        countLexError++;
         break;
      case 62 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // System.err.println("Linha: " + input_stream.getEndLine() + ", Coluna: " + input_stream.getEndColumn() + " - Constante literal inválida: começa com '\'' e termina com '\"' : " + image);
        errosLexicos.append("Erro l\u00e9xico: Constante literal inv\u00e1lida -> come\u00e7a com '\'' e termina com '\"' -> Token: ").append(image).append(", Linha: ").append(input_stream.getEndLine()).append(", Coluna: ").append(input_stream.getEndColumn()).append("\n");
        countLexError++;
         break;
      case 63 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // System.err.println("Linha: " + input_stream.getEndLine() + ", Coluna: " + input_stream.getEndColumn() + " - Número real inválido 1: " + image);
        errosLexicos.append("Erro l\u00e9xico: Constante real inv\u00e1lida -> Token: ").append(image).append(", Linha: ").append(input_stream.getEndLine()).append(", Coluna: ").append(input_stream.getEndColumn()).append("\n");
        countLexError++;
         break;
      case 64 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // System.err.println("Linha: " + input_stream.getEndLine() + ", Coluna: " + input_stream.getEndColumn() + " - Número real inválido 2: " + image);
        errosLexicos.append("Erro l\u00e9xico: Constante real deve ter no m\u00e1ximo 4 d\u00edgitos antes do ponto decimal e at\u00e9 2 d\u00edgitos ap\u00f3s o ponto -> Token: ").append(image).append(", Linha: ").append(input_stream.getEndLine()).append(", Coluna: ").append(input_stream.getEndColumn()).append("\n");
        countLexError++;
         break;
      case 65 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // System.err.println("Linha: " + input_stream.getEndLine() + ", Coluna: " + input_stream.getEndColumn() + " - Número real inválido 3: " + image);
        errosLexicos.append("Erro l\u00e9xico: Constante real deve ter no m\u00e1ximo 4 d\u00edgitos antes do ponto decimal e at\u00e9 2 d\u00edgitos ap\u00f3s o ponto -> Token: ").append(image).append(", Linha: ").append(input_stream.getEndLine()).append(", Coluna: ").append(input_stream.getEndColumn()).append("\n");
        countLexError++;
         break;
      case 66 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // System.err.println("Linha: " + input_stream.getEndLine() + ", Coluna: " + input_stream.getEndColumn() + " - Número real inválido (contém letras): " + image);
        errosLexicos.append("Erro l\u00e9xico: Constante real n\u00e3o deve conter letras -> Token: ").append(image).append(", Linha: ").append(input_stream.getEndLine()).append(", Coluna: ").append(input_stream.getEndColumn()).append("\n");
        countLexError++;
         break;
      case 67 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // System.err.println("Linha: " + input_stream.getEndLine() + ", Coluna: " + input_stream.getEndColumn() + " - Número inteiro inválido: " + image);
        errosLexicos.append("Erro l\u00e9xico: Constante inteira inv\u00e1lida -> Token: ").append(image).append(", Linha: ").append(input_stream.getEndLine()).append(", Coluna: ").append(input_stream.getEndColumn()).append("\n");
        countLexError++;
         break;
      case 68 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // System.err.println("Linha: " + input_stream.getEndLine() + ", Coluna: " + input_stream.getEndColumn() + " - Número inteiro inválido: " + image);
        errosLexicos.append("Erro l\u00e9xico: Constante inteira deve ter o tamanho m\u00e1ximo 3 -> Token: ").append(image).append(", Linha: ").append(input_stream.getEndLine()).append(", Coluna: ").append(input_stream.getEndColumn()).append("\n");
        countLexError++;
         break;
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public CompiladorTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public CompiladorTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 94; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 3 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "MULTILINE_COMMENT",
   "SINGLELINE_COMMENT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xfffffffffff001L, 0x0L, 
};
static final long[] jjtoSkip = {
   0xff00000000000ffeL, 0x1fL, 
};
static final long[] jjtoSpecial = {
   0xff00000000000000L, 0x1fL, 
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[94];
    private final int[] jjstateSet = new int[2 * 94];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
