/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO = 7;
  /** RegularExpression Id. */
  int BOOL = 12;
  /** RegularExpression Id. */
  int CHAR = 13;
  /** RegularExpression Id. */
  int CONST = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int END = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int GET = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int INT = 20;
  /** RegularExpression Id. */
  int MAKE = 21;
  /** RegularExpression Id. */
  int PUT = 22;
  /** RegularExpression Id. */
  int REAL = 23;
  /** RegularExpression Id. */
  int THEN = 24;
  /** RegularExpression Id. */
  int TRUE = 25;
  /** RegularExpression Id. */
  int VAR = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int DO = 28;
  /** RegularExpression Id. */
  int PONTO = 29;
  /** RegularExpression Id. */
  int VIRGULA = 30;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 31;
  /** RegularExpression Id. */
  int DOISPONTOS = 32;
  /** RegularExpression Id. */
  int IGUAL = 33;
  /** RegularExpression Id. */
  int ATRIBUICAO = 34;
  /** RegularExpression Id. */
  int PARENESQ = 35;
  /** RegularExpression Id. */
  int PARENDIR = 36;
  /** RegularExpression Id. */
  int MAIS = 37;
  /** RegularExpression Id. */
  int MENOS = 38;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 39;
  /** RegularExpression Id. */
  int DIVISAO = 40;
  /** RegularExpression Id. */
  int POTENCIA = 41;
  /** RegularExpression Id. */
  int DIVISAOINTEIRA = 42;
  /** RegularExpression Id. */
  int RESTODIVISAOINTEIRA = 43;
  /** RegularExpression Id. */
  int DIFERENTE = 44;
  /** RegularExpression Id. */
  int MENOR = 45;
  /** RegularExpression Id. */
  int MAIOR = 46;
  /** RegularExpression Id. */
  int MENORIGUAL = 47;
  /** RegularExpression Id. */
  int MAIORIGUAL = 48;
  /** RegularExpression Id. */
  int E = 49;
  /** RegularExpression Id. */
  int OU = 50;
  /** RegularExpression Id. */
  int NAO = 51;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 52;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_REAL = 53;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_INTEIRA = 54;
  /** RegularExpression Id. */
  int CONSTANTE_LITERAL = 55;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 56;
  /** RegularExpression Id. */
  int INVALID_IDENTIFIER = 57;
  /** RegularExpression Id. */
  int INVALID_LITERAL = 58;
  /** RegularExpression Id. */
  int INVALID_LITERAL_UNTERMINATED_DQUOTE = 59;
  /** RegularExpression Id. */
  int INVALID_LITERAL_UNTERMINATED_SQUOTE = 60;
  /** RegularExpression Id. */
  int INVALID_LITERAL_MISMATCH_DQUOTE_SQUOTE = 61;
  /** RegularExpression Id. */
  int INVALID_LITERAL_MISMATCH_SQUOTE_DQUOTE = 62;
  /** RegularExpression Id. */
  int INVALID_REAL = 63;
  /** RegularExpression Id. */
  int INVALID_REAL_NUMBER_SIZE = 64;
  /** RegularExpression Id. */
  int INVALID_REAL_NUMBER_DIGITS_AFTER = 65;
  /** RegularExpression Id. */
  int INVALID_REAL_NUMBER_WITH_LETTERS = 66;
  /** RegularExpression Id. */
  int INVALID_INTEGER = 67;
  /** RegularExpression Id. */
  int INVALID_INTEGER_SIZE = 68;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MULTILINE_COMMENT = 1;
  /** Lexical state. */
  int SINGLELINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "\"/*\"",
    "<token of kind 8>",
    "\"*/\"",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"bool\"",
    "\"char\"",
    "\"const\"",
    "\"else\"",
    "\"end\"",
    "\"false\"",
    "\"get\"",
    "\"if\"",
    "\"int\"",
    "\"make\"",
    "\"put\"",
    "\"real\"",
    "\"then\"",
    "\"true\"",
    "\"var\"",
    "\"while\"",
    "\"do\"",
    "\".\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"=\"",
    "\"->\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"%\"",
    "\"%%\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "<IDENTIFICADOR>",
    "<CONSTANTE_NUMERICA_REAL>",
    "<CONSTANTE_NUMERICA_INTEIRA>",
    "<CONSTANTE_LITERAL>",
    "<INVALID_LEXICAL>",
    "<INVALID_IDENTIFIER>",
    "<INVALID_LITERAL>",
    "<INVALID_LITERAL_UNTERMINATED_DQUOTE>",
    "<INVALID_LITERAL_UNTERMINATED_SQUOTE>",
    "<INVALID_LITERAL_MISMATCH_DQUOTE_SQUOTE>",
    "<INVALID_LITERAL_MISMATCH_SQUOTE_DQUOTE>",
    "<INVALID_REAL>",
    "<INVALID_REAL_NUMBER_SIZE>",
    "<INVALID_REAL_NUMBER_DIGITS_AFTER>",
    "<INVALID_REAL_NUMBER_WITH_LETTERS>",
    "<INVALID_INTEGER>",
    "<INVALID_INTEGER_SIZE>",
  };

}
